name: Checkpoints

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        java: ['11', '17', '19']
        distribution: ['temurin']
        gradle: ['7.6.2']
      fail-fast: false
    name: JAVA ${{ matrix.distribution }} ${{ matrix.java }} OS ${{ matrix.os }} Gradle ${{ matrix.gradle }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: set NOW env
        run: echo "NOW=$(date +'%d.%m.%Y')" >> $GITHUB_ENV
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle }}
      - name: Build mainnet checkpoints
        run: ./tools/build-checkpoints --net=PROD
      - name: Build testnet checkpoints
        run: ./tools/build-checkpoints --net=TEST
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: checkpoints-${{ env.NOW }}
          path: |
            tools/checkpoints.txt
            tools/checkpoints-testnet.txt
          if-no-files-found: error
          retention-days: 7
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: checkpoints-${{ env.NOW }}
